[project]
org-name = "hemikak"
version = "1.0.2"

license= ["Apache 2.0"]
authors= ["Hemika Kodikara"]
keywords= ["toml", "config"]
repository= "https://github.com/hemikak/toml"

[platform]
target = "java8"

  [[platform.libraries]]
  artifactId = "toml4j"
  version = "0.7.2"
  path = "./libs/toml4j-0.7.2.jar"
  groupId = "com.moandjiezana.toml"
  module = "toml4j"

  [[platform.libraries]]
  artifactId = "gson"
  version = "2.8.1"
  path = "./libs/gson-2.8.1.jar"
  groupId = "com.google.code.gson"
  module = "toml4j"
